### ISSUE TITLE
When run train_shape.sh, the training just stuck there, any clues?

### ISSUE THREAD

**Issue by Edwardmark** [junyanz/VON#15] opened 2019-04-18 02:00 UTC
Hi, I use the Dockerfile and train the shape gan, it runs just right at the start, but it stuck there without any log as follows, and the GPU utility stays 0%, could you give a hit about it?  
![image](https://user-images.githubusercontent.com/15247551/56331896-afa5bb00-61c0-11e9-828f-38e456dbc865.png)
It stucks at epoch 19 forever, but I don't know why.

**Comment by junyanz** [comment] 2019-04-18 15:46
I haven't' seen this issue before. What will happen if you restart the training from this epoch?

**Comment by ztzhang** [comment] 2019-04-18 15:54
I used to encounter this in other projects, which seems to be some multiprocessing conflict between some version of opencv/numpy with Pytorch. However, from my experience, this is usually occasional and hard to reproduce. Setting num_workers=0 for all the data loaders is a fix tho.

You can refer to [this pytorch issue](https://github.com/pytorch/pytorch/issues/1355) for more details. Closing this now.

**Closed as completed** 2019-04-18 15:55 UTC
